// <auto-generated />
using System;
using FridgeMealPlanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FridgeMealPlanner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722084652_AddCookedMeals")]
    partial class AddCookedMeals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.3.25171.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FridgeMealPlanner.Models.CookedMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Portions")
                        .HasColumnType("integer");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("CookedMeals");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.FridgeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BestBeforeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UserId");

                    b.ToTable("FridgeItems");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("DensityGPerMl")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Meat",
                            DensityGPerMl = 1.05m,
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Grains",
                            DensityGPerMl = 0.85m,
                            Name = "Rice"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Vegetables",
                            DensityGPerMl = 0.74m,
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Vegetables",
                            DensityGPerMl = 1.10m,
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Vegetables",
                            DensityGPerMl = 1.00m,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Oils",
                            DensityGPerMl = 0.92m,
                            Name = "Olive Oil"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Dairy",
                            DensityGPerMl = 1.03m,
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Dairy",
                            DensityGPerMl = 1.03m,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Dairy",
                            DensityGPerMl = 0.91m,
                            Name = "Butter"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Baking",
                            DensityGPerMl = 0.53m,
                            Name = "Flour"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Grains",
                            DensityGPerMl = 0.60m,
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Vegetables",
                            DensityGPerMl = 0.51m,
                            Name = "Bell Pepper"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Vegetables",
                            DensityGPerMl = 0.64m,
                            Name = "Carrot"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Vegetables",
                            DensityGPerMl = 0.63m,
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Dairy",
                            DensityGPerMl = 1.10m,
                            Name = "Cheese"
                        });
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CookedMealId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CookedMealId");

                    b.HasIndex("RecipeId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quick and healthy chicken stir-fry with bell peppers and broccoli",
                            Instructions = "1. Cut chicken into strips. 2. Stir-fry chicken in oil. 3. Add sliced peppers and broccoli. 4. Add soy sauce and serve over rice.",
                            IsAiGenerated = false,
                            Name = "Chicken Stir-Fry",
                            PrepTimeMinutes = 25,
                            Servings = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classic tomato pasta with garlic and fresh basil",
                            Instructions = "1. Cook pasta according to package. 2. Sauté garlic in olive oil. 3. Add chopped tomatoes and simmer. 4. Toss with pasta and top with cheese.",
                            IsAiGenerated = false,
                            Name = "Tomato Pasta",
                            PrepTimeMinutes = 20,
                            Servings = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fluffy omelette with cheese and vegetables",
                            Instructions = "1. Beat eggs with milk. 2. Melt butter in pan. 3. Pour eggs, add cheese and veggies. 4. Fold and serve.",
                            IsAiGenerated = false,
                            Name = "Omelette",
                            PrepTimeMinutes = 10,
                            Servings = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pan-seared chicken breast with garlic butter sauce",
                            Instructions = "1. Season chicken with salt and pepper. 2. Sear in butter. 3. Add minced garlic. 4. Baste and finish in pan. Serve with rice.",
                            IsAiGenerated = false,
                            Name = "Garlic Butter Chicken",
                            PrepTimeMinutes = 30,
                            Servings = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Hearty rice bowl with roasted vegetables and egg",
                            Instructions = "1. Cook rice. 2. Roast carrots and broccoli. 3. Top with fried egg. 4. Drizzle with olive oil.",
                            IsAiGenerated = false,
                            Name = "Vegetable Rice Bowl",
                            PrepTimeMinutes = 35,
                            Servings = 2
                        });
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            Quantity = 200m,
                            RecipeId = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 12,
                            Quantity = 1m,
                            RecipeId = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 14,
                            Quantity = 100m,
                            RecipeId = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 4,
                            IngredientId = 6,
                            Quantity = 2m,
                            RecipeId = 1,
                            Unit = 4
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 2,
                            Quantity = 150m,
                            RecipeId = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 6,
                            IngredientId = 11,
                            Quantity = 200m,
                            RecipeId = 2,
                            Unit = 0
                        },
                        new
                        {
                            Id = 7,
                            IngredientId = 5,
                            Quantity = 2m,
                            RecipeId = 2,
                            Unit = 2
                        },
                        new
                        {
                            Id = 8,
                            IngredientId = 4,
                            Quantity = 2m,
                            RecipeId = 2,
                            Unit = 2
                        },
                        new
                        {
                            Id = 9,
                            IngredientId = 6,
                            Quantity = 2m,
                            RecipeId = 2,
                            Unit = 4
                        },
                        new
                        {
                            Id = 10,
                            IngredientId = 15,
                            Quantity = 30m,
                            RecipeId = 2,
                            Unit = 0
                        },
                        new
                        {
                            Id = 11,
                            IngredientId = 7,
                            Quantity = 3m,
                            RecipeId = 3,
                            Unit = 2
                        },
                        new
                        {
                            Id = 12,
                            IngredientId = 8,
                            Quantity = 2m,
                            RecipeId = 3,
                            Unit = 4
                        },
                        new
                        {
                            Id = 13,
                            IngredientId = 9,
                            Quantity = 10m,
                            RecipeId = 3,
                            Unit = 0
                        },
                        new
                        {
                            Id = 14,
                            IngredientId = 15,
                            Quantity = 20m,
                            RecipeId = 3,
                            Unit = 0
                        },
                        new
                        {
                            Id = 15,
                            IngredientId = 1,
                            Quantity = 250m,
                            RecipeId = 4,
                            Unit = 0
                        },
                        new
                        {
                            Id = 16,
                            IngredientId = 4,
                            Quantity = 4m,
                            RecipeId = 4,
                            Unit = 2
                        },
                        new
                        {
                            Id = 17,
                            IngredientId = 9,
                            Quantity = 30m,
                            RecipeId = 4,
                            Unit = 0
                        },
                        new
                        {
                            Id = 18,
                            IngredientId = 2,
                            Quantity = 150m,
                            RecipeId = 4,
                            Unit = 0
                        },
                        new
                        {
                            Id = 19,
                            IngredientId = 2,
                            Quantity = 150m,
                            RecipeId = 5,
                            Unit = 0
                        },
                        new
                        {
                            Id = 20,
                            IngredientId = 13,
                            Quantity = 100m,
                            RecipeId = 5,
                            Unit = 0
                        },
                        new
                        {
                            Id = 21,
                            IngredientId = 14,
                            Quantity = 80m,
                            RecipeId = 5,
                            Unit = 0
                        },
                        new
                        {
                            Id = 22,
                            IngredientId = 7,
                            Quantity = 1m,
                            RecipeId = 5,
                            Unit = 2
                        },
                        new
                        {
                            Id = 23,
                            IngredientId = 6,
                            Quantity = 1m,
                            RecipeId = 5,
                            Unit = 4
                        });
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.ShoppingListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Purchased")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("integer");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.UnitConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FromUnit")
                        .HasColumnType("integer");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("decimal(10,6)");

                    b.Property<int>("ToUnit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("UnitConversions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromUnit = 3,
                            Multiplier = 240m,
                            ToUnit = 1
                        },
                        new
                        {
                            Id = 2,
                            FromUnit = 4,
                            Multiplier = 15m,
                            ToUnit = 1
                        },
                        new
                        {
                            Id = 3,
                            FromUnit = 5,
                            Multiplier = 5m,
                            ToUnit = 1
                        },
                        new
                        {
                            Id = 4,
                            FromUnit = 1,
                            Multiplier = 0.0041666666666666666666666667m,
                            ToUnit = 3
                        },
                        new
                        {
                            Id = 5,
                            FromUnit = 1,
                            Multiplier = 0.0666666666666666666666666667m,
                            ToUnit = 4
                        },
                        new
                        {
                            Id = 6,
                            FromUnit = 1,
                            Multiplier = 0.2m,
                            ToUnit = 5
                        },
                        new
                        {
                            Id = 7,
                            FromUnit = 0,
                            Multiplier = 1m,
                            ToUnit = 0
                        },
                        new
                        {
                            Id = 8,
                            FromUnit = 3,
                            Multiplier = 16m,
                            ToUnit = 4
                        },
                        new
                        {
                            Id = 9,
                            FromUnit = 4,
                            Multiplier = 3m,
                            ToUnit = 5
                        },
                        new
                        {
                            Id = 10,
                            FromUnit = 3,
                            Multiplier = 48m,
                            ToUnit = 5
                        },
                        new
                        {
                            Id = 11,
                            FromUnit = 0,
                            IngredientId = 10,
                            Multiplier = 0.0083333333333333333333333333m,
                            ToUnit = 3
                        },
                        new
                        {
                            Id = 12,
                            FromUnit = 3,
                            IngredientId = 10,
                            Multiplier = 120m,
                            ToUnit = 0
                        },
                        new
                        {
                            Id = 13,
                            FromUnit = 0,
                            IngredientId = 2,
                            Multiplier = 0.005m,
                            ToUnit = 3
                        },
                        new
                        {
                            Id = 14,
                            FromUnit = 3,
                            IngredientId = 2,
                            Multiplier = 200m,
                            ToUnit = 0
                        },
                        new
                        {
                            Id = 15,
                            FromUnit = 0,
                            IngredientId = 9,
                            Multiplier = 0.0714285714285714285714285714m,
                            ToUnit = 4
                        },
                        new
                        {
                            Id = 16,
                            FromUnit = 4,
                            IngredientId = 9,
                            Multiplier = 14m,
                            ToUnit = 0
                        },
                        new
                        {
                            Id = 17,
                            FromUnit = 3,
                            Multiplier = 200m,
                            ToUnit = 0
                        },
                        new
                        {
                            Id = 18,
                            FromUnit = 0,
                            Multiplier = 0.005m,
                            ToUnit = 3
                        },
                        new
                        {
                            Id = 19,
                            FromUnit = 1,
                            Multiplier = 1m,
                            ToUnit = 0
                        },
                        new
                        {
                            Id = 20,
                            FromUnit = 0,
                            Multiplier = 1m,
                            ToUnit = 1
                        });
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.CookedMeal", b =>
                {
                    b.HasOne("FridgeMealPlanner.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.FridgeItem", b =>
                {
                    b.HasOne("FridgeMealPlanner.Models.Ingredient", "Ingredient")
                        .WithMany("FridgeItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.MealPlan", b =>
                {
                    b.HasOne("FridgeMealPlanner.Models.CookedMeal", "CookedMeal")
                        .WithMany("MealPlans")
                        .HasForeignKey("CookedMealId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FridgeMealPlanner.Models.Recipe", "Recipe")
                        .WithMany("MealPlans")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CookedMeal");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.RecipeIngredient", b =>
                {
                    b.HasOne("FridgeMealPlanner.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeMealPlanner.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.ShoppingListItem", b =>
                {
                    b.HasOne("FridgeMealPlanner.Models.ShoppingList", "ShoppingList")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.UnitConversion", b =>
                {
                    b.HasOne("FridgeMealPlanner.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.CookedMeal", b =>
                {
                    b.Navigation("MealPlans");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.Ingredient", b =>
                {
                    b.Navigation("FridgeItems");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.Recipe", b =>
                {
                    b.Navigation("MealPlans");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("FridgeMealPlanner.Models.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
